#!/usr/bin/env bash
# twsh - a twtxt client written in bash
# (c) 2019 by Anirudh Oppiliappan (@icyphox) <x@icyphox.sh>
#         and Akshay Oppiliappan (@nerdypepper) <nerdypepper@tuta.io>


# uses default as $HOME
CONFIG_DIR="$HOME"

if [[ "$OSTYPE" = "linux-gnu" ]]; then
    CONFIG_DIR="$HOME/.config/twsh"
elif [[ "$OSTYPE" = "darwin" ]]; then
    CONFIG_DIR="$HOME/Library/Preferences/com.icyphox.twsh"
fi

CONFIG="$CONFIG_DIR/twshrc"

# sourcing our config
if [[ -f "$CONFIG" ]]
then
	source "$CONFIG"
	if [[ "$TWTXT_FILE" == "" ]]
	then
		echo "twsh: unable to source config"
		exit
	fi
fi

function create_config() {
    mkdir -p "$CONFIG_DIR"
    touch "$CONFIG"
    twtxt_path=$(readlink -f "$1")
    cat << EOF > "$CONFIG"
TWTXT_FILE="$twtxt_path/twtxt.txt"
EOF
    echo "twsh: created config at $CONFIG"
    source "$CONFIG"
}

function create_twtxt() {
	if [[ -f "$TWTXT_FILE" ]]
	then
		read -p "twsh: $TWTXT_FILE exists, overwrite? [y/n]: " yn
		case $yn in
			[Yy]* ) >$TWTXT_FILE ;;
			[Nn]* ) exit ;;
			* ) echo "twsh: enter yes or no"
		esac
	else
		touch "$TWTXT_FILE"
		echo "twsh: created $TWTXT_FILE"
	fi
}

function tweet() {
	text="$1"
	date=$(date -Im)
	tweet="$date\t$text"
	echo -e "$tweet" >> "$TWTXT_FILE"
}


function help_text () {
cat << EOF
usage: twsh [options]
  -i [path]       create twtxt.txt file
  -t [text]       append tweet to twtxt.txt file
  -h              show this help text
EOF
}

while getopts :iht: options
do
    case $options in
        i) 
            # init
			create_config "$2"
            create_twtxt "$2"
            ;;
        h)
            help_text
            ;;
        t|?)
            # tweet
            tweet "$OPTARG"
            ;;
		h|*)
            help_text
            ;;
    esac
done
