#!/usr/bin/env bash
# twsh - a twtxt client written in bash
# (c) 2019 by Anirudh Oppiliappan (@icyphox) <x@icyphox.sh>
#         and Akshay Oppiliappan (@nerdypepper) <nerdypepper@tuta.io>

function tweet() {
	text="$1"
	date=$(date -Im)
	tweet="$date\t$text"
	echo -e "$tweet" >> $TWTXT_FILE
}

function create_twtxt() {
	if [ "$1" == "" ]
	then
		echo "error: requires a path"
		exit
	fi
	path="$1/twtxt.txt"
	if [ -f "$path" ]
	then
		read -p "twsh: $path exists, overwrite? [y/n]: " yn
		case $yn in
			[Yy]* ) rm "$path" && touch "$1";;
			[Nn]* ) exit;;
			* ) echo "twsh: enter yes or no"
		esac
	else
		touch "$path"
		echo "twsh: created $path"
	fi
}

function help_text () {
cat << EOF
Usage: twsh [options]
EOF
}

while getopts :i:ht: options
do
    case $options in
        i) 
            # init
            create_twtxt "$OPTARG"
            ;;
        t)
            # tweet
            tweet "$OPTARG"
            ;;
        h|?)
            help_text
            ;;
    esac
done
